export const data = [
  {
    name: "Photo 1",
    url: "/images/red.jpg",
    description: "Photo 1 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 2",
    url: "/images/peach.jpg",
    description: "Photo 2 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 3",
    url: "/images/orange.jpg",
    description: "Photo 3 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 4",
    url: "/images/yellow.jpg",
    description: "Photo 4 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 5",
    url: "/images/green.jpg",
    description: "Photo 5 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 6",
    url: "/images/blue.jpg",
    description: "Photo 6 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 7",
    url: "/images/mixed1.jpg",
    description: "Photo 7 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 8",
    url: "/images/violet.jpg",
    description: "Photo 8 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 9",
    url: "/images/mixed.jpg",
    description: "Photo 9 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
  {
    name: "Photo 10",
    url: "/images/grey.jpg",
    description: "Photo 10 description",
    date: "2023-22-06",
    type: "image/jpg",
  },
];
